//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 25. 20:22:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class Authors {

        public Authors()
        {
            this.AuthorBooks = new List<AuthorBook>();
            OnCreated();
        }

        public int author_id { get; set; }

        public string name { get; set; }

        public string nationality { get; set; }

        public string birthdate { get; set; }

        public virtual IList<AuthorBook> AuthorBooks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
