//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 25. 20:22:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class Members {

        public Members()
        {
            this.Transactions = new List<Transactions>();
            OnCreated();
        }

        public int member_id { get; set; }

        public int phone_number { get; set; }

        public string name { get; set; }

        public string username { get; set; }

        public string password { get; set; }

        public bool is_admin { get; set; }

        public virtual IList<Transactions> Transactions { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
