//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 27. 12:35:57
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class Transactions
    {

        public Transactions()
        {
            OnCreated();
        }

        public int transaction_id { get; set; }

        public DateTime borrow_date { get; set; }

        public DateTime? return_date { get; set; }

        public int book_id { get; set; }

        public int member_id { get; set; }

        public virtual Books Books2 { get; set; }

        public virtual Members Members { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
