//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 28. 15:44:15
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class AuthorBook {

        public AuthorBook()
        {
            OnCreated();
        }

        public virtual int author_id { get; set; }

        public virtual int book_id { get; set; }

        public virtual int author_order { get; set; }

        public virtual Authors Authors1 { get; set; }

        public virtual Books Books { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          AuthorBook toCompare = obj as AuthorBook;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.author_id, toCompare.author_id))
            return false;
          if (!Object.Equals(this.book_id, toCompare.book_id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + author_id.GetHashCode();
          hashCode = (hashCode * 7) + book_id.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
