//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 28. 15:44:15
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class Books {

        public Books()
        {
            this.Transactions = new List<Transactions>();
            this.AuthorBooks = new List<AuthorBook>();
            OnCreated();
        }

        public virtual int book_id { get; set; }

        public virtual string genre { get; set; }

        public virtual string title { get; set; }

        public virtual int published_year { get; set; }

        public virtual bool availability { get; set; }

        public virtual int author_id { get; set; }

        public virtual string pic_name { get; set; }

        public virtual string summary { get; set; }

        public virtual string publisher { get; set; }

        public virtual bool deleted { get; set; }

        public virtual IList<Transactions> Transactions { get; set; }

        public virtual IList<AuthorBook> AuthorBooks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
