//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 28. 15:44:15
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Library
{
    public partial class Transactions {

        public Transactions()
        {
            OnCreated();
        }

        public virtual int transaction_id { get; set; }

        public virtual DateTime borrow_date { get; set; }

        public virtual DateTime? return_date { get; set; }

        public virtual int book_id { get; set; }

        public virtual int member_id { get; set; }

        public virtual Books Books2 { get; set; }

        public virtual Members Members { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
